#ifndef ERR_HPP
#define ERR_HPP

enum Err {
    OK = 0,
    ERR_INVALID_ARGUMENTS,
    ERR_OUT_OF_MEMORY,
    ERR_ALREADY_RUNNING,
    ERR_CREATE_FILE_MAPPING,
    ERR_OPEN_FILE_MAPPING,
    ERR_CREATE_EVENT,
    ERR_OPEN_EVENT,
    ERR_GET_FOREGROUND_WINDOW,
    ERR_GET_WINDOW_THREAD_PROCESS_ID,
    ERR_OPEN_PROCESS,
    ERR_IS_WOW64_PROCESS,
    ERR_GET_MODULE_FILE_NAME,
    ERR_CREATE_PROCESS,
    ERR_WAIT_FOR_SINGLE_OBJECT,
    ERR_REGISTER_WINDOW_MESSAGE,
    ERR_MAP_VIEW_OF_FILE,
    ERR_LOAD_LIBRARY,
    ERR_GET_PROC_ADDRESS,
    ERR_CLSID_FROM_STRING,
    ERR_SET_WINDOWS_HOOK_EX,
    ERR_SEND_MESSAGE_TIMEOUT,
    ERR_SEND_MESSAGE_TIMEOUT_TIMED_OUT,
    ERR_SEND_MESSAGE_TIMEOUT_FAIL_AFTER_WAIT,
    ERR_SET_EVENT,
};

#endif /* end of include guard: ERR_HPP */
