#ifndef ERR_HPP
#define ERR_HPP

enum Err {
    OK = 0,
    ERR_INVALID_ARGUMENTS = 1,
    ERR_OUT_OF_MEMORY = 2,
    ERR_CREATE_FILE_MAPPING = 3,
    ERR_GET_FOREGROUND_WINDOW = 4,
    ERR_GET_WINDOW_THREAD_PROCESS_ID = 5,
    ERR_OPEN_PROCESS = 6,
    ERR_IS_WOW64_PROCESS = 7,
    ERR_GET_MODULE_FILE_NAME = 8,
    ERR_CREATE_PROCESS = 9,
    ERR_WAIT_FOR_SINGLE_OBJECT = 10,
    ERR_REGISTER_WINDOW_MESSAGE = 11,
    ERR_MAP_VIEW_OF_FILE = 12,
    ERR_LOAD_LIBRARY = 13,
    ERR_GET_PROC_ADDRESS = 14,
    ERR_CLSID_FROM_STRING = 15,
    ERR_SET_WINDOWS_HOOK_EX = 16,
    ERR_SEND_MESSAGE_TIMEOUT = 17,
    ERR_SEND_MESSAGE_TIMEOUT_TIMED_OUT = 18,
    ERR_SEND_MESSAGE_TIMEOUT_FAIL_AFTER_WAIT = 19,
};

#endif /* end of include guard: ERR_HPP */
